export const DEFAULT_AI_RECIPES = [
  {
    name: "Savory Oatmeal with Fried Egg and Avocado",
    emoji: "🥣",
    mealType: "breakfast",
    baseServings: 2,
    ingredients: [
      {
        name: "rolled oats",
        amount: 1,
        unit: "cup",
        category: "grains",
        purchaseItem: "18 oz canister of rolled oats",
        purchaseAmount: 5,
        purchasePrice: 4.49,
      },
      {
        name: "large eggs",
        amount: 2,
        unit: "large",
        category: "protein",
        purchaseItem: "dozen large eggs",
        purchaseAmount: 12,
        purchasePrice: 3.99,
      },
      {
        name: "avocado",
        amount: 1,
        unit: "",
        category: "produce",
        purchaseItem: "1 avocado",
        purchaseAmount: 1,
        purchasePrice: 1.29,
      },
      {
        name: "shredded cheddar cheese",
        amount: 0.5,
        unit: "cup",
        category: "dairy",
        purchaseItem: "8 oz bag shredded cheddar cheese",
        purchaseAmount: 2,
        purchasePrice: 3.49,
      },
      {
        name: "green onions",
        amount: 2,
        unit: "",
        category: "produce",
        purchaseItem: "bunch of green onions",
        purchaseAmount: 6,
        purchasePrice: 1.19,
      },
    ],
    instructions:
      "1. Cook the oats according to the package directions with a pinch of salt.\n2. Fry the eggs in a skillet until the whites are set and the yolks are cooked to your preference.\n3. Divide the oatmeal into bowls and top with cheddar, sliced avocado, green onions, and fried eggs.\n4. Season with salt and pepper and serve warm.",
  },
  {
    name: "Caprese Salad with Balsamic Glaze",
    emoji: "🍅",
    mealType: "snack",
    baseServings: 2,
    ingredients: [
      {
        name: "fresh mozzarella",
        amount: 8,
        unit: "oz",
        category: "dairy",
        purchaseItem: "8 oz ball fresh mozzarella",
        purchaseAmount: 8,
        purchasePrice: 4.99,
      },
      {
        name: "tomatoes",
        amount: 2,
        unit: "",
        category: "produce",
        purchaseItem: "2 large tomatoes",
        purchaseAmount: 2,
        purchasePrice: 2.5,
      },
      {
        name: "fresh basil",
        amount: 0.5,
        unit: "cup",
        category: "produce",
        purchaseItem: "fresh basil package",
        purchaseAmount: 1,
        purchasePrice: 2.99,
      },
      {
        name: "balsamic glaze",
        amount: 2,
        unit: "tbsp",
        category: "pantry",
        purchaseItem: "8.5 oz bottle balsamic glaze",
        purchaseAmount: 17,
        purchasePrice: 4.79,
      },
      {
        name: "olive oil",
        amount: 1,
        unit: "tbsp",
        category: "pantry",
        purchaseItem: "16.9 fl oz bottle olive oil",
        purchaseAmount: 33,
        purchasePrice: 7.99,
      },
    ],
    instructions:
      "1. Slice the tomatoes and mozzarella into even rounds.\n2. Arrange tomato, mozzarella, and basil on a plate.\n3. Drizzle with olive oil and balsamic glaze.\n4. Sprinkle with salt and pepper and serve chilled or at room temperature.",
  },
  {
    name: "Sheet Pan Sausage and Peppers",
    emoji: "🌶️",
    mealType: "dinner",
    baseServings: 4,
    ingredients: [
      {
        name: "Italian sausage links",
        amount: 1,
        unit: "lb",
        category: "protein",
        purchaseItem: "1 lb pack Italian sausage links",
        purchaseAmount: 1,
        purchasePrice: 5.49,
      },
      {
        name: "bell peppers",
        amount: 3,
        unit: "",
        category: "produce",
        purchaseItem: "3 bell peppers",
        purchaseAmount: 3,
        purchasePrice: 3.75,
      },
      {
        name: "yellow onion",
        amount: 1,
        unit: "",
        category: "produce",
        purchaseItem: "1 yellow onion",
        purchaseAmount: 1,
        purchasePrice: 0.99,
      },
      {
        name: "olive oil",
        amount: 2,
        unit: "tbsp",
        category: "pantry",
        purchaseItem: "16.9 fl oz bottle olive oil",
        purchaseAmount: 33,
        purchasePrice: 7.99,
      },
      {
        name: "hoagie rolls",
        amount: 4,
        unit: "",
        category: "grains",
        purchaseItem: "6-count pack hoagie rolls",
        purchaseAmount: 6,
        purchasePrice: 3.99,
      },
    ],
    instructions:
      "1. Heat the oven to 425°F.\n2. Slice peppers and onion, then spread them on a sheet pan with sausage links.\n3. Toss the vegetables with olive oil, salt, and pepper.\n4. Roast for 25 to 30 minutes, turning once, until sausage is cooked through.\n5. Serve in hoagie rolls or over rice.",
  },
  {
    name: "Spaghetti with Meat Sauce",
    emoji: "🍝",
    mealType: "dinner",
    baseServings: 4,
    ingredients: [
      {
        name: "spaghetti",
        amount: 1,
        unit: "lb",
        category: "grains",
        purchaseItem: "1 lb box spaghetti",
        purchaseAmount: 1,
        purchasePrice: 1.99,
      },
      {
        name: "ground beef",
        amount: 1,
        unit: "lb",
        category: "protein",
        purchaseItem: "1 lb pack ground beef",
        purchaseAmount: 1,
        purchasePrice: 5.99,
      },
      {
        name: "marinara sauce",
        amount: 24,
        unit: "oz",
        category: "pantry",
        purchaseItem: "24 oz jar marinara sauce",
        purchaseAmount: 24,
        purchasePrice: 3.49,
      },
      {
        name: "yellow onion",
        amount: 1,
        unit: "",
        category: "produce",
        purchaseItem: "1 yellow onion",
        purchaseAmount: 1,
        purchasePrice: 0.99,
      },
      {
        name: "parmesan cheese",
        amount: 0.5,
        unit: "cup",
        category: "dairy",
        purchaseItem: "5 oz grated parmesan container",
        purchaseAmount: 1.25,
        purchasePrice: 3.99,
      },
    ],
    instructions:
      "1. Boil spaghetti in salted water until al dente.\n2. Brown the ground beef with diced onion in a large skillet.\n3. Drain excess fat, then stir in marinara sauce and simmer for 10 minutes.\n4. Toss spaghetti with sauce and top with parmesan cheese.",
  },
  {
    name: "Chicken Stir-fry with Rice",
    emoji: "🥢",
    mealType: "dinner",
    baseServings: 4,
    ingredients: [
      {
        name: "chicken breast",
        amount: 1.5,
        unit: "lb",
        category: "protein",
        purchaseItem: "2 lb pack chicken breast",
        purchaseAmount: 2,
        purchasePrice: 9.49,
      },
      {
        name: "white rice",
        amount: 1.5,
        unit: "cup",
        category: "grains",
        purchaseItem: "2 lb bag white rice",
        purchaseAmount: 5,
        purchasePrice: 2.99,
      },
      {
        name: "frozen stir-fry vegetables",
        amount: 16,
        unit: "oz",
        category: "produce",
        purchaseItem: "16 oz bag frozen stir-fry vegetables",
        purchaseAmount: 16,
        purchasePrice: 2.99,
      },
      {
        name: "soy sauce",
        amount: 3,
        unit: "tbsp",
        category: "pantry",
        purchaseItem: "10 oz bottle soy sauce",
        purchaseAmount: 20,
        purchasePrice: 2.49,
      },
      {
        name: "sesame oil",
        amount: 1,
        unit: "tbsp",
        category: "pantry",
        purchaseItem: "5 oz bottle sesame oil",
        purchaseAmount: 10,
        purchasePrice: 4.99,
      },
    ],
    instructions:
      "1. Cook the rice according to package directions.\n2. Slice chicken into bite-size pieces and cook in a hot skillet until browned.\n3. Add vegetables and cook until tender-crisp.\n4. Stir in soy sauce and sesame oil.\n5. Serve the stir-fry over rice.",
  },
  {
    name: "Banana Pancakes",
    emoji: "🥞",
    mealType: "breakfast",
    baseServings: 4,
    ingredients: [
      {
        name: "pancake mix",
        amount: 2,
        unit: "cup",
        category: "pantry",
        purchaseItem: "32 oz box pancake mix",
        purchaseAmount: 8,
        purchasePrice: 3.79,
      },
      {
        name: "milk",
        amount: 1.5,
        unit: "cup",
        category: "dairy",
        purchaseItem: "half gallon milk",
        purchaseAmount: 8,
        purchasePrice: 2.99,
      },
      {
        name: "large eggs",
        amount: 2,
        unit: "large",
        category: "protein",
        purchaseItem: "dozen large eggs",
        purchaseAmount: 12,
        purchasePrice: 3.99,
      },
      {
        name: "bananas",
        amount: 2,
        unit: "",
        category: "produce",
        purchaseItem: "bunch of bananas",
        purchaseAmount: 6,
        purchasePrice: 1.79,
      },
      {
        name: "maple syrup",
        amount: 0.5,
        unit: "cup",
        category: "pantry",
        purchaseItem: "12 oz bottle maple syrup",
        purchaseAmount: 1.5,
        purchasePrice: 6.99,
      },
    ],
    instructions:
      "1. Whisk pancake mix, milk, and eggs until combined.\n2. Mash one banana into the batter and slice the second banana for topping.\n3. Cook pancakes on a greased skillet until bubbles form, then flip.\n4. Serve with banana slices and maple syrup.",
  },
  {
    name: "Tuna Salad Sandwiches",
    emoji: "🥪",
    mealType: "lunch",
    baseServings: 4,
    ingredients: [
      {
        name: "canned tuna",
        amount: 10,
        unit: "oz",
        category: "protein",
        purchaseItem: "two 5 oz cans tuna",
        purchaseAmount: 10,
        purchasePrice: 2.98,
      },
      {
        name: "mayonnaise",
        amount: 0.25,
        unit: "cup",
        category: "pantry",
        purchaseItem: "30 oz jar mayonnaise",
        purchaseAmount: 3.75,
        purchasePrice: 4.99,
      },
      {
        name: "celery",
        amount: 2,
        unit: "stalks",
        category: "produce",
        purchaseItem: "bunch of celery",
        purchaseAmount: 10,
        purchasePrice: 2.29,
      },
      {
        name: "sandwich bread",
        amount: 8,
        unit: "slices",
        category: "grains",
        purchaseItem: "loaf sandwich bread",
        purchaseAmount: 20,
        purchasePrice: 2.79,
      },
      {
        name: "romaine lettuce",
        amount: 4,
        unit: "leaves",
        category: "produce",
        purchaseItem: "head of romaine lettuce",
        purchaseAmount: 10,
        purchasePrice: 2.99,
      },
    ],
    instructions:
      "1. Drain tuna and mix it with mayonnaise and diced celery.\n2. Season with salt and pepper.\n3. Layer lettuce and tuna salad on sandwich bread.\n4. Slice sandwiches and serve chilled.",
  },
  {
    name: "Lemon Herb Roasted Chicken and Veggies",
    emoji: "🍗",
    mealType: "dinner",
    baseServings: 4,
    ingredients: [
      {
        name: "chicken thighs",
        amount: 2,
        unit: "lb",
        category: "protein",
        purchaseItem: "2 lb pack chicken thighs",
        purchaseAmount: 2,
        purchasePrice: 7.99,
      },
      {
        name: "baby potatoes",
        amount: 1.5,
        unit: "lb",
        category: "produce",
        purchaseItem: "1.5 lb bag baby potatoes",
        purchaseAmount: 1.5,
        purchasePrice: 3.99,
      },
      {
        name: "carrots",
        amount: 1,
        unit: "lb",
        category: "produce",
        purchaseItem: "1 lb bag carrots",
        purchaseAmount: 1,
        purchasePrice: 1.49,
      },
      {
        name: "lemon",
        amount: 1,
        unit: "",
        category: "produce",
        purchaseItem: "1 lemon",
        purchaseAmount: 1,
        purchasePrice: 0.79,
      },
      {
        name: "olive oil",
        amount: 2,
        unit: "tbsp",
        category: "pantry",
        purchaseItem: "16.9 fl oz bottle olive oil",
        purchaseAmount: 33,
        purchasePrice: 7.99,
      },
    ],
    instructions:
      "1. Heat the oven to 425°F.\n2. Toss potatoes and carrots with olive oil, lemon juice, salt, pepper, and herbs.\n3. Place chicken thighs on the pan and season them with the same lemon herb mixture.\n4. Roast for 35 to 40 minutes until the chicken reaches 165°F.\n5. Rest for 5 minutes before serving.",
  },
  {
    name: "Black Bean Tacos",
    emoji: "🌮",
    mealType: "dinner",
    baseServings: 4,
    ingredients: [
      {
        name: "black beans",
        amount: 30,
        unit: "oz",
        category: "pantry",
        purchaseItem: "two 15 oz cans black beans",
        purchaseAmount: 30,
        purchasePrice: 2.38,
      },
      {
        name: "corn tortillas",
        amount: 8,
        unit: "",
        category: "grains",
        purchaseItem: "10-count pack corn tortillas",
        purchaseAmount: 10,
        purchasePrice: 2.49,
      },
      {
        name: "shredded cheddar cheese",
        amount: 1,
        unit: "cup",
        category: "dairy",
        purchaseItem: "8 oz bag shredded cheddar cheese",
        purchaseAmount: 2,
        purchasePrice: 3.49,
      },
      {
        name: "salsa",
        amount: 1,
        unit: "cup",
        category: "pantry",
        purchaseItem: "16 oz jar salsa",
        purchaseAmount: 2,
        purchasePrice: 2.99,
      },
      {
        name: "avocado",
        amount: 1,
        unit: "",
        category: "produce",
        purchaseItem: "1 avocado",
        purchaseAmount: 1,
        purchasePrice: 1.29,
      },
    ],
    instructions:
      "1. Warm black beans in a skillet with salt, pepper, and taco seasoning if desired.\n2. Heat tortillas in a dry skillet until soft.\n3. Fill tortillas with beans, cheese, salsa, and sliced avocado.\n4. Serve immediately with lime wedges if available.",
  },
  {
    name: "Greek Yogurt with Berries and Granola",
    emoji: "🍓",
    mealType: "snack",
    baseServings: 1,
    ingredients: [
      {
        name: "Greek yogurt",
        amount: 1,
        unit: "cup",
        category: "dairy",
        purchaseItem: "32 oz tub Greek yogurt",
        purchaseAmount: 4,
        purchasePrice: 5.49,
      },
      {
        name: "mixed berries",
        amount: 0.75,
        unit: "cup",
        category: "produce",
        purchaseItem: "12 oz package mixed berries",
        purchaseAmount: 2,
        purchasePrice: 4.49,
      },
      {
        name: "granola",
        amount: 0.5,
        unit: "cup",
        category: "grains",
        purchaseItem: "12 oz bag granola",
        purchaseAmount: 6,
        purchasePrice: 4.99,
      },
      {
        name: "honey",
        amount: 1,
        unit: "tbsp",
        category: "pantry",
        purchaseItem: "12 oz bottle honey",
        purchaseAmount: 24,
        purchasePrice: 5.99,
      },
    ],
    instructions:
      "1. Spoon Greek yogurt into a bowl.\n2. Top with berries and granola.\n3. Drizzle honey over the top.\n4. Serve immediately.",
  },
];
